oaslam_wrapper:
  ros__parameters:
    image_topic: /upper/realsense_upper/color/image_raw
    pose_topic: /oa_slam/camera_pose
    world_frame_id: map
    camera_id: mono0
    vocabulary_file: /opt/OA-SLAM/Vocabulary/ORBvoc.txt
    camera_config_file: /opt/OA-SLAM/ros2/oaslam_ros2_wrapper/config/slam_camera.yaml
    observation_mode: onnx
    # onnx_model_path: ""
    onnx_model_path: "/opt/OA-SLAM/Data/yolov5m_640x480.onnx"
    ignored_categories_file: ""
    relocalization_mode: points+objects
    use_viewer: true
    use_sim_time: true
