x-oaslam-build: &oaslam-build
  context: ..
  dockerfile: docker/Dockerfile
  pull: false
  args:
    CUDA_VERSION: ${CUDA_VERSION}
    CUDNN_FLAVOR: ${CUDNN_FLAVOR}
    UBUNTU_VERSION: ${UBUNTU_VERSION}
    OPENCV_VERSION: ${OPENCV_VERSION}
    NPROC: ${NPROC}
    CUDA_ARCH_BIN: ${CUDA_ARCH_BIN}
    ROS_DISTRO: ${ROS_DISTRO:-humble}
    HTTP_PROXY: ${DOCKER_BUILD_HTTP_PROXY:-}
    HTTPS_PROXY: ${DOCKER_BUILD_HTTPS_PROXY:-}
    ALL_PROXY: ${DOCKER_BUILD_ALL_PROXY:-}
    NO_PROXY: ${DOCKER_BUILD_NO_PROXY:-}
    http_proxy: ${DOCKER_BUILD_HTTP_PROXY:-}
    https_proxy: ${DOCKER_BUILD_HTTPS_PROXY:-}
    all_proxy: ${DOCKER_BUILD_ALL_PROXY:-}
    no_proxy: ${DOCKER_BUILD_NO_PROXY:-}

services:
  oa-slam:
    build: *oaslam-build
    image: oa-slam:latest
    container_name: oa-slam
    privileged: true
    environment:
      DISPLAY: ${DISPLAY:-:0}
      QT_X11_NO_MITSHM: "1"
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-all}
      HOME: /root
      ROS_HOME: /root/.ros
      ROS_DISTRO: ${ROS_DISTRO:-humble}
      ROS_WS: /opt/oaslam_ros2_ws
      NPROC: ${NPROC:-16}
      OASLAM_CPP_BUILD_DIR: /opt/OA-SLAM/build
      OASLAM_CPP_INSTALL_PREFIX: /opt/oaslam_artifacts/cpp/install
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../CMakeLists.txt:/opt/OA-SLAM/CMakeLists.txt:ro
      - ../cmake:/opt/OA-SLAM/cmake:ro
      - ../include:/opt/OA-SLAM/include:ro
      - ../src:/opt/OA-SLAM/src:ro
      - ../ros2:/opt/OA-SLAM/ros2:ro
      - ../ros2/oaslam_ros2_wrapper:/opt/oaslam_ros2_ws/src/oaslam_ros2_wrapper:ro
      - ../../SharedSemanticMap/ros2/shared_semantic_map_interfaces:/opt/oaslam_ros2_ws/src/shared_semantic_map_interfaces:ro
      - ../Data:/opt/OA-SLAM/Data
      - ../Cameras:/opt/OA-SLAM/Cameras:ro
      - ./:/opt/OA-SLAM/docker:ro
      # voluems
      - oaslam_cpp_build:/opt/OA-SLAM/build
      - oaslam_cpp_install:/opt/oaslam_artifacts/cpp/install
      - oaslam_ros2_build:/opt/oaslam_ros2_ws/build
      - oaslam_ros2_install:/opt/oaslam_ros2_ws/install
      - oaslam_ros2_log:/opt/oaslam_ros2_ws/log
      - oaslam_ros_home:/root/.ros
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    init: true
    gpus: all
    working_dir: /opt/OA-SLAM
    command: ["sleep", "infinity"]

volumes:
  oaslam_cpp_build:
  oaslam_cpp_install:
  oaslam_ros2_build:
  oaslam_ros2_install:
  oaslam_ros2_log:
  oaslam_ros_home:
